# Acme/DemoBundle/Resources/config/admin.yml
services:
    sonata.admin.employee:
        class: Medicina\InasistenciasBundle\Admin\EmployeeAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Contenido", label: "Empleados" }
        arguments:
            - ~
            - Medicina\InasistenciasBundle\Entity\Employee
            - MedicinaInasistenciasBundle:EmployeeCRUD
            # MedicinaInasistenciasBundle:CRUD
        calls:
            - [ setTranslationDomain, [MedicinaInasistenciasBundle]]
            - [ addChild, [@sonata.admin.compensatory_part]]
            - [ addChild, [@sonata.admin.compensatory]]
            # [ setTemplate, [ausente, MedicinaInasistenciasBundle:InasistenciaAdmin:edit.html.twig]]

    sonata.admin.office:
        class: Medicina\InasistenciasBundle\Admin\OfficeAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Contenido", label: "Oficinas" }
        arguments:
            - ~
            - Medicina\InasistenciasBundle\Entity\Office
            - ~
        calls:
            - [ setTranslationDomain, [MedicinaInasistenciasBundle]]

    sonata.admin.employee_type:
        class: Medicina\InasistenciasBundle\Admin\EmployeeTypeAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Contenido", label: "Tipos de Empleado" }
        arguments:
            - ~
            - Medicina\InasistenciasBundle\Entity\EmployeeType
            - ~
        calls:
            - [ setTranslationDomain, [MedicinaInasistenciasBundle]]

    sonata.admin.compensatory_part:
        class: Medicina\InasistenciasBundle\Admin\CompensatoryPartAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Contenido", label: "Módulos de Tiempo" }
        arguments:
            - ~
            - Medicina\InasistenciasBundle\Entity\CompensatoryPart
            - ~
            #- MedicinaInasistenciasBundle:CompensatoryCRUD
        calls:
            - [setTranslationDomain, [MedicinaInasistenciasBundle]]
    

    sonata.admin.compensatory:
        class: Medicina\InasistenciasBundle\Admin\CompensatoryAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Contenido", label: "Compensatorios" }
        arguments:
            - ~
            - Medicina\InasistenciasBundle\Entity\Compensatory
            - ~
            #- MedicinaInasistenciasBundle:CompensatoryCRUD
        calls:
            - [setTranslationDomain, [MedicinaInasistenciasBundle]]